language: node_js
addons:
  chrome: stable
env:
  matrix:
    - TEST_SUITE=build
    - TEST_SUITE=unit
node_js:
  - 10
  - stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_7f62a7100786_key -iv $encrypted_7f62a7100786_iv -in environment.prod.ts.enc -out ./src/environments/environment.prod.ts -d
- cp ./src/environments/environment.example.ts ./src/environments/environment.ts
after_install:
- npm run postinstall
script:
- npm run test:$TEST_SUITE
after_success:
- npm install coveralls && cat ./coverage/lcov.info | coveralls
